### ISSUE TITLE
Escape forward slashes inside JSON response

### ISSUE THREAD

**Issue by erikyao** [biothings/biothings_explorer_web#40]
MWE: [http://biothings.io/explorer/api/v2/directinput2output?input_prefix=go&output_prefix=goDescription&input_value=0042535](http://biothings.io/explorer/api/v2/directinput2output?input_prefix=go&output_prefix=goDescription&input_value=0042535)

Got `json['data'][0]['output']['object']['id']`:

> "monocytes during acute inflammation and which is responsible for a diverse range of signaling events within cells, leading to necrosis or apoptosis."

Expecting:

> "goDescription: Any process that activates or increases the frequency, rate or extent of the chemical reactions and pathways resulting in the formation of tumor necrosis factor, an inflammatory cytokine produced by macrophages/monocytes during acute inflammation and which is responsible for a diverse range of signaling events within cells, leading to necrosis or apoptosis. "

The part preceding the forward slash in front of "monocytes" is truncated.

Is it because of JSON-LD? Thanks!

**Comment by kevinxin90** [comment]
@erikyao Let me look into it!!

**Comment by kevinxin90** [comment]
@erikyao 
I have located where the bug comes from. It's not related to JSON-LD. Instead, it is related to how I organized the final output. Now the bug has been fixed. Please try it again if you have time! 

I will fix the bug which is related to the special character colon ":" tomorrow. That one is related to JSON-LD. And I have found a solution to it. Will keep you updated!

Thanks!

**Comment by kevinxin90** [comment]
Also managed to fix the colon ':' issue related to JSON-LD, now it's fully functional. The issue is initially raised when testing https://github.com/kevinxin90/RTX_BioThings_Explorer/blob/master/test_QueryEBIOLSExtended.py#L72.
Cheers!

**Comment by erikyao** [comment]
Thank you so much, Kevin!
